platform :android do
  lane :deploy do
    supply(
      json_key: ENV["SUPPLY_JSON_KEY"],
      package_name: "com.UnknownGames.MoveTheSquare",
      track: "internal",
      aab: ENV["AAB_PATH"]
    )
  end
end