platform :android do
  lane :deploy do
    supply(
      json_key: ENV["SUPPLY_JSON_KEY"],
      package_name: "com.UnknownGames.MoveTheSquare",
      apk: Dir["Builds/Android/*.apk"].first,
      track: "open"
    )
  end
end